---
title: "C28163 | Microsoft Docs"
ms.custom: ""
ms.date: "11/04/2016"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "vs-devops-test"
ms.tgt_pltfrm: ""
ms.topic: "article"
f1_keywords: 
  - "C28163"
helpviewer_keywords: 
  - "C28163"
ms.assetid: 24fecbde-1c96-4a45-82f7-9f47cfc0ef11
caps.latest.revision: 3
author: "corob-msft"
ms.author: "corob"
manager: "ghogen"
caps.handback.revision: 3
---
# C28163
[!INCLUDE[vs2017banner](../code-quality/includes/vs2017banner.md)]

avertissement C28163 : La fonction ne doit jamais être appelée depuis l'intérieur d'un bloc try\/except  
  
 Cet avertissement est stocké lorsqu'une fonction est d'un type ne doit jamais être placé dans un bloc d' `try/except` est trouvé dans un bloc d' `try/except` .  L'outil d'analyse du code a trouvé au moins un chemin d'accès dans lequel la fonction appelée se trouve dans un bloc `try/except` .