---
title: C6320 | Documents Microsoft
ms.custom: 
ms.date: 11/04/2016
ms.reviewer: 
ms.suite: 
ms.technology:
- vs-ide-code-analysis
ms.tgt_pltfrm: 
ms.topic: article
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
caps.latest.revision: 
author: mikeblome
ms.author: mblome
manager: ghogen
ms.workload:
- multiple
ms.openlocfilehash: dbf498f943fb4f6e446cd254e7ca5f844ee0ec68
ms.sourcegitcommit: 32f1a690fc445f9586d53698fc82c7debd784eeb
ms.translationtype: MT
ms.contentlocale: fr-FR
ms.lasthandoff: 12/22/2017
---
# <a name="c6320"></a>C6320
avertissement C6320 : expression de filtre d’exception est la constante EXCEPTION_EXECUTE_HANDLER. Cela peut masquer des exceptions qui n’étaient pas destinées à être gérées  
  
 Cet avertissement indique l’effet secondaire de l’utilisation de la constante EXCEPTION_EXECUTE_HANDLER dans un bloc __except. Dans ce cas, l’instruction dans le \_bloc _except s’exécute toujours pour gérer l’exception, y compris les exceptions que vous ne souhaitez pas gérer dans une fonction particulière. Il est recommandé de vérifier l’exception avant de la gérer.  
  
## <a name="example"></a>Exemple  
 Le code suivant génère cet avertissement car le bloc __except tente de gérer les exceptions de tous les types :  
  
```  
#include <stdio.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;  // might cause access violation exception  
      // code ...  
   }   
   __except(EXCEPTION_EXECUTE_HANDLER) // warning  
   {   
      puts("in except");   
      // code ...  
   }   
}   
```  
  
 Pour corriger cet avertissement, utilisez `GetExceptionCode` pour vérifier une exception particulière avant de gérer, comme indiqué dans le code suivant :  
  
```  
#include <stdio.h>   
#include <windows.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;    // might cause access violation exception   
      // code ...  
   }   
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)  
   {   
      puts("in except");   
      // code ...  
   }   
}  
```  
  
## <a name="see-also"></a>Voir aussi  
 [try-except, instruction](/cpp/cpp/try-except-statement)